export const glasses = [
    "hurricane glass",
    "shot glass",
    "balloon glass",
    "copper mug",
    "coffee mug",
    "irish coffee cup",
    "beer mug",
    "martini glass",
    "pitcher",
    "cocktail glass",
    "pint glass",
    "margarita glass",
    "white wine glass",
    "collins glass",
    "old fashioned glass",
    "whiskey glass",
    "wine glass",
    "beer pilsner",
    "mason jar",
    "highball glass",
    "jar",
    "nick and nora glass",
    "punch bowl",
    "coupe glass",
    "brandy snifter",
    "whiskey sour glass",
    "margarita coupette glass",
    "champagne flute",
    "pousse cafe glass"
];